[package]
name = "mvc"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
bevy = { version = "0.15.2", features = ["jpeg", "png", "hdr"] }
accesskit = "0.17.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
